swagger: "2.0"
info:
  version: 1.0.0
  title: portal-scheduling
  description: Educational project
basePath: /api/v1/scheduling
tags:
  - name: ScheduleItens
    description: Simple schedule item endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ScheduleItemBody:
    type: object
    title: schedule item
    required:
      - title
      - date
      - type
    properties:
      title:
        type: string
      date:
        type: string
      subject:
        type: string
      type:
        type: string

paths:
  /schedule-itens:
    get:
      tags:
        - ScheduleItens
      description: Fetch all schedule itens
      responses:
        200:
          description: Returns all schedule itens
    post:
      tags:
        - ScheduleItens
      description: Create a new schedule item
      parameters:
        - name: schedule item
          in: body
          description: an schedule item
          required: true
          schema: 
            $ref: "#/definitions/ScheduleItemBody"
      responses:
        200:
          description: Returns all schedule itens

  /schedule-itens/{id}:
    get:
      tags:
        - ScheduleItens
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the schedule item to retrieve
          type: string
      responses:
        200:
          description: Return the schedule item with the specified id
        404:
          description: Schedule item not found
    delete:
      tags:
        - ScheduleItens
      description: Delete a existent schedule item
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the schedule item to delete
          type: string
      responses:
        200:
          description: Return the schedule item that was deleted
        404:
          description: Schedule item not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification